plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.107'
    id 'idea'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

repositories {
    maven { url 'https://cursemaven.com' }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
        }
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    compileOnly "me.alfie.immersiveenchanting:immersiveenchanting:${immersive_enchanting_version}"
    compileOnly "curse.maven:alfinolib-1554698:8596074"
    localRuntime "me.alfie.immersiveenchanting:immersiveenchanting:${immersive_enchanting_version}"
    localRuntime files('../immersive-enchanting/lib/alfinolib-1.2.0-neoforge-1.21.1.jar')
}

var generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    var replaceProperties = [
            minecraft_version             : minecraft_version,
            minecraft_version_range       : minecraft_version_range,
            neo_version                   : neo_version,
            loader_version_range          : loader_version_range,
            mod_id                        : mod_id,
            mod_name                      : mod_name,
            mod_license                   : mod_license,
            mod_version                   : mod_version,
            mod_authors                   : mod_authors,
            mod_description               : mod_description,
            immersive_enchanting_version  : immersive_enchanting_version
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from 'src/main/templates'
    into 'build/generated/sources/modMetadata'
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
